#8 Remove state check for upgrading
cloudogu/redis pull request #9
Opened 2024-06-05 09:16 UTC by jelemux

since that state is never set

Resolves #8

2024-06-26 14:14 UTC, kahoona77 requested changes
Update to use new doguctl v0.12.0

2024-06-26 14:14 UTC, kahoona77 commented on CHANGELOG.md
> +- [#8] Upgrade base image to 3.20.1-1
```suggestion
- [#8] Upgrade base image to 3.20.1-2
```

2024-06-26 14:14 UTC, kahoona77 commented on Dockerfile
> +FROM registry.cloudogu.com/official/base:3.20.1-1
```suggestion
FROM registry.cloudogu.com/official/base:3.20.1-2
```

2024-07-02 14:10 UTC, ppxl commented on Dockerfile
> +    REDIS_VERSION="7.2.5-r0" \
Is this major version upgrade planned? It's a heavy thing to roll this up during a very simple change.

I know Redis 6.2 sucks but for this change I'd rather do the light lifting and the major upgrade in another change when we know the consequences with consuming dogus

2024-07-03 11:16 UTC, ppxl commented on Dockerfile
> +    REDIS_VERSION="7.2.5-r0" \
Reduced to the latest available Redis version in the given alpine minor version

2024-07-03 13:40 UTC, kahoona77 approved these changes

2024-07-03 13:41 UTC, kahoona77 approved these changes
LGTM

2024-07-03 13:41 UTC, merged